"""empty message

Revision ID: 2bc3f19a1d8a
Revises: 
Create Date: 2023-06-20 13:51:30.780870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc3f19a1d8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('formula', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['formula'], ['formula.title'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
