"""empty message

Revision ID: 8136503de444
Revises: 2bc3f19a1d8a
Create Date: 2023-06-20 16:01:30.825856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8136503de444'
down_revision = '2bc3f19a1d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date_tome', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'date_tome')
    # ### end Alembic commands ###
